name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Intel oneAPI
      uses: intel-actions/setup-oneapi@v1
      with:
        components: intel-oneapi-compiler-fortran

    - name: Configure Intel oneAPI environment
      run: |
        source /opt/intel/oneapi/setvars.sh
        echo "INTEL_ONEAPI_PATH=/opt/intel/oneapi" >> $GITHUB_ENV

    - name: Create directories
      run: |
        mkdir -p obj
        mkdir -p bin

    - name: Build all executables
      run: |
        source /opt/intel/oneapi/setvars.sh
        make all

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: dushin-binaries
        path: |
          bin/dushin
          bin/displace
          bin/compare-geom

    - name: Clean
      run: make clean

