name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-hpckit:latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Intel oneAPI environment
        shell: bash
        run: |
          source /opt/intel/oneapi/setvars.sh --force
          printenv >> $GITHUB_ENV

      - name: Create directories
        run: |
          mkdir -p obj
          mkdir -p bin

      - name: Build all executables
        run: |
          make all

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: dushin-binaries
          path: |
            bin/dushin
            bin/displace
            bin/compare-geom

      - name: Clean
        run: make clean

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - {compiler: intel, version: '2023.1'}
          - {compiler: intel-classic, version: '2021.9'}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Fortran compiler
        uses: awvwgk/setup-fortran@v1
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: dushin-binaries

      - name: Run tests
        run: |
          ./bin/dushin --version
          ./bin/displace --version
          ./bin/compare-geom --version
