name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install gfortran
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran
          
      - name: Create directories
        run: |
          mkdir -p src/obj
          mkdir -p src/bin
          
      - name: Build all executables
        working-directory: src
        shell: bash
        run: |
          gfortran --version
          make all
          
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: dushin-binaries
          path: |
            src/bin/dushin
            src/bin/displace
            src/bin/compare-geom
            
      - name: Clean
        working-directory: src
        shell: bash
        run: make clean
