jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: intel/oneapi:latest

    steps:
    - uses: actions/checkout@v4

    - name: Create directories
      run: |
        mkdir -p obj
        mkdir -p bin

    - name: Build all executables
      run: |
        source /opt/intel/oneapi/setvars.sh
        make all

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: dushin-binaries
        path: |
          bin/dushin
          bin/displace
          bin/compare-geom

    - name: Clean
      run: make clean