name: Build and Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: intel/oneapi-hpckit:latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Intel oneAPI environment
        shell: bash
        run: |
          . /opt/intel/oneapi/setvars.sh
          echo "source_script=. /opt/intel/oneapi/setvars.sh" >> $GITHUB_ENV
      - name: Create directories
        run: |
          mkdir -p src/obj
          mkdir -p src/bin
      - name: Build all executables
        working-directory: src
        shell: bash
        run: |
          ${{ env.source_script }}
          which ifort
          ifort --version
          make all
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: dushin-binaries
          path: |
            src/bin/dushin
            src/bin/displace
            src/bin/compare-geom
      - name: Clean
        working-directory: src
        shell: bash
        run: |
          ${{ env.source_script }}
          make clean